version: 0.2

#$CODEBUILD_SRC_DIR is is a given env var

env:
  variables:
    BUILD_ENV: "prod"
phases:
  install:
    commands:
      - echo "Upgrading NPM"
      - npm install -g npm
      - echo "Changing to Source Directory"
      - cd src
      - echo "Installing NPM dependencies"
      - npm install --unsafe-perm
      - echo "Installing Angular CLI"
      - npm install -g --unsafe-perm @angular/cli@latest
  pre_build:
    commands:
      - echo "pre-build commands..."
      - "[[ -d ../src ]] || echo 'Missing src dir'"
      - "[[ -d ../scaffolding ]] || echo 'Missing scaffolding dir'"
      - "[[ -d ../package ]] || echo 'Missing package dir'"
  build:
    commands:
      - echo "build command..."
      - ng build --env=${BUILD_ENV}
  post_build:
    commands:
      - cd ..
      - mkdir ./package/swagger-ui
      - cp -r ./src/src/swagger-ui/* ./package/swagger-ui/
      - sed  -n '/BEGIN SWAGGER/,/END SWAGGER/{/END SWAGGER/!p}' ./scaffolding/transforms/swagger_v2_child_managed_services.yml > ./package/swagger-ui/swagger.yml
      - cp -r ./src/dist/* ./package/
      - cp -r ./scaffolding/* ./package/
artifacts:
  files:
    - ./package/**/*
